### ISSUE TITLE
🔷 [Epic] Arbitrary dependencies

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#16]
BOS components should be able to leverage the full ecosystem of NPM packages. This is referred to as "arbitrary" dependencies because there has been prior discussion of supporting a subset of NPM packages in the current VM which have undergone a vetting process
```[tasklist]
### Tasks
- [ ] https://github.com/near/bos-web-engine/issues/90
- [ ] https://github.com/near/bos-web-engine/issues/93
- [ ] https://github.com/near/bos-web-engine/issues/96
- [ ] https://github.com/near/bos-web-engine/issues/138
```

**Comment by andy-haynes** [comment]
Once #158 is merged (breaking change), we'll have this implemented according to our discussion.

Invariably this will be followed by lots of work around interoperability and module compatibility, but this should be a good jumping off point for supporting basic modules and further exploring these concerns.
