### ISSUE TITLE
🔷 [Epic] Use separate SocialDB namespace for BWE components

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#177]
## Description
Over the course of coming months, there will be several targets which components may be built for:

- VM
- BOS Web Engine pre-release
- BOS Web Engine production

In order to enable separation between these sets of components, we are going to start writing to different namespaces in SocialDB.

For the VM, components are written to `<author>/widget/<component name>`
For BWE pre-release, we will start with `<author>/component_alpha/<component name>`
```[tasklist]
### Tasks
- [ ] https://github.com/near/bos-web-engine/issues/178
- [ ] https://github.com/near/bos-web-engine/issues/180
- [ ] https://github.com/bos-cli-rs/bos-cli-rs/issues/79
- [ ] https://github.com/near/bos-web-engine/issues/179
```
