### ISSUE TITLE
Alpha test prep

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#182]
```[tasklist]
### Tasks
- [ ] https://github.com/near/bos-web-engine/issues/183
- [ ] https://github.com/near/bos-web-engine/issues/184
- [ ] https://github.com/near/bos-web-engine/issues/185
- [ ] https://github.com/near/bos-web-engine/issues/177
- [ ] https://github.com/near/bos-web-engine/issues/215
- [ ] https://github.com/near/bos-web-engine/issues/8
- [ ] https://github.com/near/bos-web-engine/issues/9
- [ ] https://github.com/near/bos-web-engine/issues/220
- [ ] https://github.com/near/bos-web-engine/issues/230
- [ ] https://github.com/near/bos-web-engine/issues/234
- [ ] https://github.com/near/bos-web-engine/issues/298
```
