### ISSUE TITLE
🔷 [Epic] Polish demos

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#240]
## Description
With the addition of CSS support, we should take some time to polish any demos we will be showing off for the alpha, starting with the social feed demo
```[tasklist]
### Tasks
- [ ] https://github.com/near/bos-web-engine/issues/256
- [ ] https://github.com/near/bos-web-engine/issues/257
- [ ] https://github.com/near/bos-web-engine/issues/258
- [ ] https://github.com/near/bos-web-engine/issues/286
- [ ] https://github.com/near/bos-web-engine/issues/287
- [ ] https://github.com/near/bos-web-engine/issues/296
```
