### ISSUE TITLE
Troubleshoot Vercel build

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#35]
```[tasklist]
### Tasks
- [ ] https://github.com/near/bos-web-engine/issues/36
- [ ] https://github.com/near/bos-web-engine/issues/46
- [ ] https://github.com/near/bos-web-engine/issues/47
```

**Comment by mpeterdev** [comment]
Some progress made, the `@bos-web-engine/container` ref failure was most likely the result of erroneous caching, because a redeploy which skips the build cache executed successfully. We need to dig into our turborepo cache settings to prevent similar issues in the future
