### ISSUE TITLE
🔷 [Epic] CSS module/file support

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#8]
Allow writing a vanilla CSS module/file alongside a component or exporting a set of vanilla CSS as a string from Component code
```[tasklist]
### Tasks
- [ ] https://github.com/near/bos-web-engine/issues/234
- [ ] https://github.com/near/bos-web-engine/issues/229
- [ ] https://github.com/near/bos-web-engine/issues/252
- [ ] https://github.com/near/bos-web-engine/issues/249
```

**Comment by mpeterdev** [comment]
Solution discussion: #130
