### ISSUE TITLE
🔷 [Epic] Development+Demo Improvements

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#81]
```[tasklist]
### Tasks
- [ ] https://github.com/near/bos-web-engine/issues/56
- [ ] https://github.com/near/bos-web-engine/issues/62
- [ ] https://github.com/near/bos-web-engine/issues/70
- [ ] https://github.com/near/bos-web-engine/issues/86
```
